grid_0001.Children.Add((new GridRow(0, new View[] { PleaseWaitWhileScanning, MainStudioSet })).Row);
PleaseWaitWhileScanning.Children.Add((new GridRow(0, new View[] { Progress, textblock_0002 })).Row);
MainStudioSet.Children.Add((new GridRow(0, new View[] { grid_0007, gEditStudioSetColumn2, gEditStudioSetSearchResult, grid_0671 })).Row);
grid_0007.Children.Add((new GridRow(0, new View[] { grid_0028, grid_0029, grid_0035, grid_0041, grid_0047, grid_0053, grid_0058, grid_0064, grid_0070, grid_0076, grid_0082, grid_0088, grid_0094, grid_0100, grid_0106, grid_0112, grid_0116, grid_0120, grid_0124 })).Row);
grid_0028.Children.Add((new GridRow(0, new View[] { cbStudioSetSelector })).Row);
grid_0029.Children.Add((new GridRow(0, new View[] { grid_0030 })).Row);
grid_0030.Children.Add((new GridRow(0, new View[] { textblock_0034, cbToneControl1 })).Row);
grid_0035.Children.Add((new GridRow(0, new View[] { grid_0036 })).Row);
grid_0036.Children.Add((new GridRow(0, new View[] { textblock_0040, cbToneControl2 })).Row);
grid_0041.Children.Add((new GridRow(0, new View[] { grid_0042 })).Row);
grid_0042.Children.Add((new GridRow(0, new View[] { textblock_0046, cbToneControl3 })).Row);
grid_0047.Children.Add((new GridRow(0, new View[] { grid_0048 })).Row);
grid_0048.Children.Add((new GridRow(0, new View[] { textblock_0052, cbToneControl4 })).Row);
grid_0053.Children.Add((new GridRow(0, new View[] { grid_0054 })).Row);
grid_0054.Children.Add((new GridRow(0, new View[] { tbTempo, slTempo })).Row);
grid_0058.Children.Add((new GridRow(0, new View[] { grid_0059 })).Row);
grid_0059.Children.Add((new GridRow(0, new View[] { textblock_0063, cbSoloPart })).Row);
grid_0064.Children.Add((new GridRow(0, new View[] { grid_0065 })).Row);
grid_0065.Children.Add((new GridRow(0, new View[] { cbReverb, cbChorus, cbMasterEQ })).Row);
grid_0070.Children.Add((new GridRow(0, new View[] { grid_0071 })).Row);
grid_0071.Children.Add((new GridRow(0, new View[] { textblock_0075, cbDrumCompEQPart })).Row);
grid_0076.Children.Add((new GridRow(0, new View[] { grid_0077 })).Row);
grid_0077.Children.Add((new GridRow(0, new View[] { textblock_0081, cbDrumCompEQ1OutputAssign })).Row);
grid_0082.Children.Add((new GridRow(0, new View[] { grid_0083 })).Row);
grid_0083.Children.Add((new GridRow(0, new View[] { textblock_0087, cbDrumCompEQ2OutputAssign })).Row);
grid_0088.Children.Add((new GridRow(0, new View[] { grid_0089 })).Row);
grid_0089.Children.Add((new GridRow(0, new View[] { textblock_0093, cbDrumCompEQ3OutputAssign })).Row);
grid_0094.Children.Add((new GridRow(0, new View[] { grid_0095 })).Row);
grid_0095.Children.Add((new GridRow(0, new View[] { textblock_0099, cbDrumCompEQ4OutputAssign })).Row);
grid_0100.Children.Add((new GridRow(0, new View[] { grid_0101 })).Row);
grid_0101.Children.Add((new GridRow(0, new View[] { textblock_0105, cbDrumCompEQ5OutputAssign })).Row);
grid_0106.Children.Add((new GridRow(0, new View[] { grid_0107 })).Row);
grid_0107.Children.Add((new GridRow(0, new View[] { textblock_0111, cbDrumCompEQ6OutputAssign })).Row);
grid_0112.Children.Add((new GridRow(0, new View[] { cbDrumCompEQ, cbExtPartMute })).Row);
grid_0116.Children.Add((new GridRow(0, new View[] { tbExtPartLevel, slExtPartLevel })).Row);
grid_0120.Children.Add((new GridRow(0, new View[] { tbExtPartChorusSend, slExtPartChorusSend })).Row);
grid_0124.Children.Add((new GridRow(0, new View[] { tbExtPartReverbSend, slExtPartReverbSend })).Row);
gEditStudioSetColumn2.Children.Add((new GridRow(0, new View[] { grid_0131, SystemCommonSettings, VoiceReserve, Chorus, ChorusReverb, StudioSetMotionalSurround, StudioSetMasterEQ })).Row);
grid_0131.Children.Add((new GridRow(0, new View[] { cbColumn2Selector })).Row);
SystemCommonSettings.Children.Add((new GridRow(0, new View[] { grid_0151, grid_0155, grid_0159, grid_0163, grid_0164, grid_0169, grid_0173, grid_0177, grid_0181, grid_0185, grid_0190, grid_0195, grid_0200, grid_0205, grid_0206, grid_0207, grid_0208, grid_0209 })).Row);
grid_0151.Children.Add((new GridRow(0, new View[] { tbSystemCommonMasterTune, slSystemCommonMasterTune })).Row);
grid_0155.Children.Add((new GridRow(0, new View[] { tbSystemCommonMasterKeyShift, slSystemCommonMasterKeyShift })).Row);
grid_0159.Children.Add((new GridRow(0, new View[] { tbSystemCommonMasterLevel, slSystemCommonMasterLevel })).Row);
grid_0163.Children.Add((new GridRow(0, new View[] { cbSystemCommonScaleTuneSwitch })).Row);
grid_0164.Children.Add((new GridRow(0, new View[] { textblock_0168, cbSystemCommonStudioSetControlChannel })).Row);
grid_0169.Children.Add((new GridRow(0, new View[] { tbSystemCommonSystemControlSource1, cbSystemCommonSystemControlSource1 })).Row);
grid_0173.Children.Add((new GridRow(0, new View[] { tbSystemCommonSystemControlSource2, cbSystemCommonSystemControlSource2 })).Row);
grid_0177.Children.Add((new GridRow(0, new View[] { tbSystemCommonSystemControlSource3, cbSystemCommonSystemControlSource3 })).Row);
grid_0181.Children.Add((new GridRow(0, new View[] { tbSystemCommonSystemControlSource4, cbSystemCommonSystemControlSource4 })).Row);
grid_0185.Children.Add((new GridRow(0, new View[] { textblock_0189, cbSystemCommonControlSource })).Row);
grid_0190.Children.Add((new GridRow(0, new View[] { textblock_0194, cbSystemCommonSystemClockSource })).Row);
grid_0195.Children.Add((new GridRow(0, new View[] { textblock_0199, slSystemCommonSystemTempo })).Row);
grid_0200.Children.Add((new GridRow(0, new View[] { textblock_0204, cbSystemCommonTempoAssignSource })).Row);
grid_0205.Children.Add((new GridRow(0, new View[] { cbSystemCommonReceiveProgramChange })).Row);
grid_0206.Children.Add((new GridRow(0, new View[] { cbSystemCommonReceiveBankSelect })).Row);
grid_0207.Children.Add((new GridRow(0, new View[] { cbSystemCommonSurroundCenterSpeakerSwitch })).Row);
grid_0208.Children.Add((new GridRow(0, new View[] { cbSystemCommonSurroundSubWooferSwitch })).Row);
grid_0209.Children.Add((new GridRow(0, new View[] { textblock_0213, cbSystemCommonStereoOutputMode })).Row);
VoiceReserve.Children.Add((new GridRow(0, new View[] { grid_0231, grid_0236, grid_0241, grid_0246, grid_0251, grid_0256, grid_0261, grid_0266, grid_0271, grid_0276, grid_0281, grid_0286, grid_0291, grid_0296, grid_0301, grid_0306 })).Row);
grid_0231.Children.Add((new GridRow(0, new View[] { textblock_0235, slVoiceReserve01 })).Row);
grid_0236.Children.Add((new GridRow(0, new View[] { textblock_0240, slVoiceReserve02 })).Row);
grid_0241.Children.Add((new GridRow(0, new View[] { textblock_0245, slVoiceReserve03 })).Row);
grid_0246.Children.Add((new GridRow(0, new View[] { textblock_0250, slVoiceReserve04 })).Row);
grid_0251.Children.Add((new GridRow(0, new View[] { textblock_0255, slVoiceReserve05 })).Row);
grid_0256.Children.Add((new GridRow(0, new View[] { textblock_0260, slVoiceReserve06 })).Row);
grid_0261.Children.Add((new GridRow(0, new View[] { textblock_0265, slVoiceReserve07 })).Row);
grid_0266.Children.Add((new GridRow(0, new View[] { textblock_0270, slVoiceReserve08 })).Row);
grid_0271.Children.Add((new GridRow(0, new View[] { textblock_0275, slVoiceReserve09 })).Row);
grid_0276.Children.Add((new GridRow(0, new View[] { textblock_0280, slVoiceReserve10 })).Row);
grid_0281.Children.Add((new GridRow(0, new View[] { textblock_0285, slVoiceReserve11 })).Row);
grid_0286.Children.Add((new GridRow(0, new View[] { textblock_0290, slVoiceReserve12 })).Row);
grid_0291.Children.Add((new GridRow(0, new View[] { textblock_0295, slVoiceReserve13 })).Row);
grid_0296.Children.Add((new GridRow(0, new View[] { textblock_0300, slVoiceReserve14 })).Row);
grid_0301.Children.Add((new GridRow(0, new View[] { textblock_0305, slVoiceReserve15 })).Row);
grid_0306.Children.Add((new GridRow(0, new View[] { textblock_0310, slVoiceReserve16 })).Row);
Chorus.Children.Add((new GridRow(0, new View[] { grid_0317, grid_0322, grid_0326, grid_0331, ChorusChorus, ChorusDelay, ChorusGM2Chorus })).Row);
grid_0317.Children.Add((new GridRow(0, new View[] { textblock_0321, cbStudioSetChorusType })).Row);
grid_0322.Children.Add((new GridRow(0, new View[] { tbChorusLevel, slChorusLevel })).Row);
grid_0326.Children.Add((new GridRow(0, new View[] { textblock_0330, cbChorusOutputAssign })).Row);
grid_0331.Children.Add((new GridRow(0, new View[] { textblock_0335, cbChorusOutputSelect })).Row);
ChorusChorus.Children.Add((new GridRow(0, new View[] { grid_0346, grid_0350, grid_0354, grid_0358, ChorusRateHz, ChorusRateNote, ChorusDepth, grid_0371, grid_0375 })).Row);
grid_0346.Children.Add((new GridRow(0, new View[] { tbChorusChorusFilterType, cbChorusChorusFilterType })).Row);
grid_0350.Children.Add((new GridRow(0, new View[] { tbChorusChorusFilterCutoffFrequency, cbChorusChorusFilterCutoffFrequency })).Row);
grid_0354.Children.Add((new GridRow(0, new View[] { tbChorusChorusPreDelay, slChorusChorusPreDelay })).Row);
grid_0358.Children.Add((new GridRow(0, new View[] { tbChorusChorusRateHzNote, cbChorusChorusRateHzNote })).Row);
ChorusRateHz.Children.Add((new GridRow(0, new View[] { tbChorusChorusRateHz, slChorusChorusRateHz })).Row);
ChorusRateNote.Children.Add((new GridRow(0, new View[] { tbChorusChorusRateNote, slChorusChorusRateNote })).Row);
ChorusDepth.Children.Add((new GridRow(0, new View[] { tbChorusChorusDepth, slChorusChorusDepth })).Row);
grid_0371.Children.Add((new GridRow(0, new View[] { tbChorusChorusPhase, slChorusChorusPhase })).Row);
grid_0375.Children.Add((new GridRow(0, new View[] { tbChorusChorusFeedback, slChorusChorusFeedback })).Row);
ChorusDelay.Children.Add((new GridRow(0, new View[] { grid_0392, ChorusDelayLeftHz, ChorusDelayLeftNote, grid_0403, ChorusDelayRightHz, ChorusDelayRightNote, grid_0414, ChorusDelayCenterHz, ChorusDelayCenterNote, grid_0425, grid_0429, grid_0433, grid_0437, grid_0441 })).Row);
grid_0392.Children.Add((new GridRow(0, new View[] { textblock_0396, cbChorusDelayLeftMsNote })).Row);
ChorusDelayLeftHz.Children.Add((new GridRow(0, new View[] { tbChorusDelayLeftHz, slChorusDelayLeftHz })).Row);
ChorusDelayLeftNote.Children.Add((new GridRow(0, new View[] { tbChorusDelayLeftNote, slChorusDelayLeftNote })).Row);
grid_0403.Children.Add((new GridRow(0, new View[] { textblock_0407, cbChorusDelayRightMsNote })).Row);
ChorusDelayRightHz.Children.Add((new GridRow(0, new View[] { tbChorusDelayRightHz, slChorusDelayRightHz })).Row);
ChorusDelayRightNote.Children.Add((new GridRow(0, new View[] { tbChorusDelayRightNote, slChorusDelayRightNote })).Row);
grid_0414.Children.Add((new GridRow(0, new View[] { textblock_0418, cbChorusDelayCenterMsNote })).Row);
ChorusDelayCenterHz.Children.Add((new GridRow(0, new View[] { tbChorusDelayCenterHz, slChorusDelayCenterHz })).Row);
ChorusDelayCenterNote.Children.Add((new GridRow(0, new View[] { tbChorusDelayCenterNote, slChorusDelayCenterNote })).Row);
grid_0425.Children.Add((new GridRow(0, new View[] { tbChorusDelayCenterFeedback, slChorusDelayCenterFeedback })).Row);
grid_0429.Children.Add((new GridRow(0, new View[] { tbChorusDelayHFDamp, cbChorusDelayHFDamp })).Row);
grid_0433.Children.Add((new GridRow(0, new View[] { tbChorusDelayLeftLevel, slChorusDelayLeftLevel })).Row);
grid_0437.Children.Add((new GridRow(0, new View[] { tbChorusDelayRightLevel, slChorusDelayRightLevel })).Row);
grid_0441.Children.Add((new GridRow(0, new View[] { tbChorusDelayCenterLevel, slChorusDelayCenterLevel })).Row);
ChorusGM2Chorus.Children.Add((new GridRow(0, new View[] { ChorusGM2ChorusPreLPF, ChorusGM2ChorusLevel, ChorusGM2ChorusFeedback, ChorusGM2ChorusDelay, ChorusGM2ChorusRate, ChorusGM2ChorusDepth, ChorusGM2ChorusSendLevelToReverb })).Row);
ChorusGM2ChorusPreLPF.Children.Add((new GridRow(0, new View[] { tbChorusGM2ChorusPreLPF, slChorusGM2ChorusPreLPF })).Row);
ChorusGM2ChorusLevel.Children.Add((new GridRow(0, new View[] { tbChorusGM2ChorusLevel, slChorusGM2ChorusLevel })).Row);
ChorusGM2ChorusFeedback.Children.Add((new GridRow(0, new View[] { tbChorusGM2ChorusFeedback, slChorusGM2ChorusFeedback })).Row);
ChorusGM2ChorusDelay.Children.Add((new GridRow(0, new View[] { tbChorusGM2ChorusDelay, slChorusGM2ChorusDelay })).Row);
ChorusGM2ChorusRate.Children.Add((new GridRow(0, new View[] { tbChorusGM2ChorusRate, slChorusGM2ChorusRate })).Row);
ChorusGM2ChorusDepth.Children.Add((new GridRow(0, new View[] { tbChorusGM2ChorusDepth, slChorusGM2ChorusDepth })).Row);
ChorusGM2ChorusSendLevelToReverb.Children.Add((new GridRow(0, new View[] { tbChorusGM2ChorusSendLevelToReverb, slChorusGM2ChorusSendLevelToReverb })).Row);
ChorusReverb.Children.Add((new GridRow(0, new View[] { grid_0480, grid_0485, grid_0489, StudioSetReverb, StudioSetReverbGM2 })).Row);
grid_0480.Children.Add((new GridRow(0, new View[] { textblock_0484, cbStudioSetReverbType })).Row);
grid_0485.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbLevel, slStudioSetReverbLevel })).Row);
grid_0489.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbOutputAssign, cbStudioSetReverbOutputAssign })).Row);
StudioSetReverb.Children.Add((new GridRow(0, new View[] { grid_0503, grid_0507, grid_0511, grid_0515, grid_0519, grid_0523, grid_0527, grid_0531 })).Row);
grid_0503.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbPreDelay, slStudioSetReverbPreDelay })).Row);
grid_0507.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbTime, slStudioSetReverbTime })).Row);
grid_0511.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbDensity, slStudioSetReverbDensity })).Row);
grid_0515.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbDiffusion, slStudioSetReverbDiffusion })).Row);
grid_0519.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbLFDamp, slStudioSetReverbLFDamp })).Row);
grid_0523.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbHFDamp, slStudioSetReverbHFDamp })).Row);
grid_0527.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbSpread, slStudioSetReverbSpread })).Row);
grid_0531.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbTone, slStudioSetReverbTone })).Row);
StudioSetReverbGM2.Children.Add((new GridRow(0, new View[] { grid_0539, grid_0543 })).Row);
grid_0539.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbGM2Character, slStudioSetReverbGM2Character })).Row);
grid_0543.Children.Add((new GridRow(0, new View[] { tbStudioSetReverbGM2Time, slStudioSetReverbGM2Time })).Row);
StudioSetMotionalSurround.Children.Add((new GridRow(0, new View[] { grid_0566, grid_0567, grid_0572, grid_0576, grid_0581, grid_0585, grid_0589, grid_0593, grid_0597, grid_0601, grid_0605, grid_0609, grid_0614 })).Row);
grid_0566.Children.Add((new GridRow(0, new View[] { cbStudioSetMotionalSurround })).Row);
grid_0567.Children.Add((new GridRow(0, new View[] { textblock_0571, cbStudioSetMotionalSurroundRoomType })).Row);
grid_0572.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundAmbienceLevel, slStudioSetMotionalSurroundAmbienceLevel })).Row);
grid_0576.Children.Add((new GridRow(0, new View[] { textblock_0580, cbStudioSetMotionalSurroundRoomSize })).Row);
grid_0581.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundAmbienceTime, slStudioSetMotionalSurroundAmbienceTime })).Row);
grid_0585.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundAmbienceDensity, slStudioSetMotionalSurroundAmbienceDensity })).Row);
grid_0589.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundAmbienceHFDamp, slStudioSetMotionalSurroundAmbienceHFDamp })).Row);
grid_0593.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundExternalPartLR, slStudioSetMotionalSurroundExternalPartLR })).Row);
grid_0597.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundExternalPartFB, slStudioSetMotionalSurroundExternalPartFB })).Row);
grid_0601.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundExtPartWidth, slStudioSetMotionalSurroundExtPartWidth })).Row);
grid_0605.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundExtpartAmbienceSend, slStudioSetMotionalSurroundExtpartAmbienceSend })).Row);
grid_0609.Children.Add((new GridRow(0, new View[] { textblock_0613, cbStudioSetMotionalSurroundExtPartControl })).Row);
grid_0614.Children.Add((new GridRow(0, new View[] { tbStudioSetMotionalSurroundDepth, slStudioSetMotionalSurroundDepth })).Row);
StudioSetMasterEQ.Children.Add((new GridRow(0, new View[] { grid_0643, grid_0647, grid_0651, grid_0655, grid_0659, grid_0663, grid_0667 })).Row);
grid_0643.Children.Add((new GridRow(0, new View[] { tbStudioSetMasterEqLowFreq, cbStudioSetMasterEqLowFreq })).Row);
grid_0647.Children.Add((new GridRow(0, new View[] { tbStudioSetMasterEqLowGain, slStudioSetMasterEqLowGain })).Row);
grid_0651.Children.Add((new GridRow(0, new View[] { tbStudioSetMasterEqMidFreq, cbStudioSetMasterEqMidFreq })).Row);
grid_0655.Children.Add((new GridRow(0, new View[] { tbStudioSetMasterEqMidGain, slStudioSetMasterEqMidGain })).Row);
grid_0659.Children.Add((new GridRow(0, new View[] { tbStudioSetMasterEqMidQ, cbStudioSetMasterEqMidQ })).Row);
grid_0663.Children.Add((new GridRow(0, new View[] { tbStudioSetMasterEqHighFreq, cbStudioSetMasterEqHighFreq })).Row);
grid_0667.Children.Add((new GridRow(0, new View[] { tbStudioSetMasterEqHighGain, slStudioSetMasterEqHighGain })).Row);
gEditStudioSetSearchResult.Children.Add((new GridRow(0, new View[] { lvSearchResults })).Row);
grid_0671.Children.Add((new GridRow(0, new View[] { grid_0678, PartSettings, grid_0679, StudioSetPartSettings1, StudioSetPartSettings2, StudioSetPartKeyboard, StudioSetPartScaleTune, StudioSetPartMidi, StudioSetPartMotionalSurround, StudioSetPartEQ, Buttons })).Row);
grid_0678.Children.Add((new GridRow(0, new View[] { cbStudioSetPartSelector })).Row);
PartSettings.Children.Add((new GridRow(0, new View[] { cbStudioSetPartSubSelector })).Row);
grid_0679.Children.Add((new GridRow(0, new View[] { StudioSetCurrentToneName })).Row);
StudioSetPartSettings1.Children.Add((new GridRow(0, new View[] { grid_0695, grid_0699, grid_0703, grid_0708, grid_0712, grid_0716, grid_0720, grid_0724, grid_0728, grid_0732, grid_0737, grid_0742, grid_0746, grid_0751 })).Row);
grid_0695.Children.Add((new GridRow(0, new View[] { cbStudioSetPartSettings1Receive, cbStudioSetPartSettings1ReceiveChannel })).Row);
grid_0699.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1Group, cbStudioSetPartSettings1Group })).Row);
grid_0703.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1Category, cbStudioSetPartSettings1Category })).Row);
grid_0708.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1Program, cbStudioSetPartSettings1Program })).Row);
grid_0712.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1Search, cbStudioSetPartSettings1Search })).Row);
grid_0716.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1Level, slStudioSetPartSettings1Level })).Row);
grid_0720.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1Pan, slStudioSetPartSettings1Pan })).Row);
grid_0724.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1CoarseTune, slStudioSetPartSettings1CoarseTune })).Row);
grid_0728.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1FineTune, slStudioSetPartSettings1FineTune })).Row);
grid_0732.Children.Add((new GridRow(0, new View[] { textblock_0736, cbStudioSetPartSettings1MonoPoly })).Row);
grid_0737.Children.Add((new GridRow(0, new View[] { textblock_0741, cbStudioSetPartSettings1Legato })).Row);
grid_0742.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1PitchBendRange, slStudioSetPartSettings1PitchBendRange })).Row);
grid_0746.Children.Add((new GridRow(0, new View[] { textblock_0750, cbStudioSetPartSettings1Portamento })).Row);
grid_0751.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings1PortamentoTime, slStudioSetPartSettings1PortamentoTime })).Row);
StudioSetPartSettings2.Children.Add((new GridRow(0, new View[] { grid_0773, grid_0777, grid_0781, grid_0785, grid_0789, grid_0793, grid_0797, grid_0801, grid_0805, grid_0809, grid_0813 })).Row);
grid_0773.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2CutoffOffset, slStudioSetPartSettings2CutoffOffset })).Row);
grid_0777.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2ResonanceOffset, slStudioSetPartSettings2ResonanceOffset })).Row);
grid_0781.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2AttackTimeOffset, slStudioSetPartSettings2AttackTimeOffset })).Row);
grid_0785.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2DecayTimeOffset, slStudioSetPartSettings2DecayTimeOffset })).Row);
grid_0789.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2ReleaseTimeOffset, slStudioSetPartSettings2ReleaseTimeOffset })).Row);
grid_0793.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2VibratoRate, slStudioSetPartSettings2VibratoRate })).Row);
grid_0797.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2VibratoDepth, slStudioSetPartSettings2VibratoDepth })).Row);
grid_0801.Children.Add((new GridRow(0, new View[] { tbStudioSetPartSettings2VibratoDelay, slStudioSetPartSettings2VibratoDelay })).Row);
grid_0805.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEffectsChorusSendLevel, slStudioSetPartEffectsChorusSendLevel })).Row);
grid_0809.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEffectsReverbSendLevel, slStudioSetPartEffectsReverbSendLevel })).Row);
grid_0813.Children.Add((new GridRow(0, new View[] { textblock_0817, cbStudioSetPartEffectsOutputAssign })).Row);
StudioSetPartKeyboard.Children.Add((new GridRow(0, new View[] { grid_0831, grid_0835, grid_0839, grid_0843, grid_0847, grid_0851, grid_0855, grid_0859, grid_0863, grid_0867, grid_0871, grid_0872 })).Row);
grid_0831.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardOctaveShift, slStudioSetPartKeyboardOctaveShift })).Row);
grid_0835.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardVelocitySenseOffset, slStudioSetPartKeyboardVelocitySenseOffset })).Row);
grid_0839.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardRangeLower, slStudioSetPartKeyboardRangeLower })).Row);
grid_0843.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardRangeUpper, slStudioSetPartKeyboardRangeUpper })).Row);
grid_0847.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardFadeWidthLower, slStudioSetPartKeyboardFadeWidthLower })).Row);
grid_0851.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardFadeWidthUpper, slStudioSetPartKeyboardFadeWidthUpper })).Row);
grid_0855.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardVelocityRangeLower, slStudioSetPartKeyboardVelocityRangeLower })).Row);
grid_0859.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardVelocityRangeUpper, slStudioSetPartKeyboardVelocityRangeUpper })).Row);
grid_0863.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardVelocityFadeWidthLower, slStudioSetPartKeyboardVelocityFadeWidthLower })).Row);
grid_0867.Children.Add((new GridRow(0, new View[] { tbStudioSetPartKeyboardVelocityFadeWidthUpper, slStudioSetPartKeyboardVelocityFadeWidthUpper })).Row);
grid_0871.Children.Add((new GridRow(0, new View[] { cbStudioSetPartKeyboardMute })).Row);
grid_0872.Children.Add((new GridRow(0, new View[] { textblock_0876, cbStudioSetPartKeyboardVelocityCurveType })).Row);
StudioSetPartScaleTune.Children.Add((new GridRow(0, new View[] { grid_0892, grid_0897, grid_0902, grid_0906, grid_0910, grid_0914, grid_0918, grid_0922, grid_0926, grid_0930, grid_0934, grid_0938, grid_0942, grid_0946 })).Row);
grid_0892.Children.Add((new GridRow(0, new View[] { textblock_0896, cbStudioSetPartScaleTuneType })).Row);
grid_0897.Children.Add((new GridRow(0, new View[] { textblock_0901, cbStudioSetPartScaleTuneKey })).Row);
grid_0902.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneC, slStudioSetPartScaleTuneC })).Row);
grid_0906.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneCi, slStudioSetPartScaleTuneCi })).Row);
grid_0910.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneD, slStudioSetPartScaleTuneD })).Row);
grid_0914.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneDi, slStudioSetPartScaleTuneDi })).Row);
grid_0918.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneE, slStudioSetPartScaleTuneE })).Row);
grid_0922.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneF, slStudioSetPartScaleTuneF })).Row);
grid_0926.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneFi, slStudioSetPartScaleTuneFi })).Row);
grid_0930.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneG, slStudioSetPartScaleTuneG })).Row);
grid_0934.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneGi, slStudioSetPartScaleTuneGi })).Row);
grid_0938.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneA, slStudioSetPartScaleTuneA })).Row);
grid_0942.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneAi, slStudioSetPartScaleTuneAi })).Row);
grid_0946.Children.Add((new GridRow(0, new View[] { tbStudioSetPartScaleTuneB, slStudioSetPartScaleTuneB })).Row);
StudioSetPartMidi.Children.Add((new GridRow(0, new View[] { grid_0962, grid_0963, grid_0964, grid_0965, grid_0966, grid_0967, grid_0968, grid_0969, grid_0970, grid_0971, grid_0972 })).Row);
grid_0962.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiPhaseLock })).Row);
grid_0963.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceiveProgramChange })).Row);
grid_0964.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceiveBankSelect })).Row);
grid_0965.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceivePitchBend })).Row);
grid_0966.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceivePolyphonicKeyPressure })).Row);
grid_0967.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceiveChannelPressure })).Row);
grid_0968.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceiveModulation })).Row);
grid_0969.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceiveVolume })).Row);
grid_0970.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceivePan })).Row);
grid_0971.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceiveExpression })).Row);
grid_0972.Children.Add((new GridRow(0, new View[] { cbStudioSetPartMidiReceiveHold1 })).Row);
StudioSetPartMotionalSurround.Children.Add((new GridRow(0, new View[] { grid_0979, grid_0983, grid_0987, grid_0991 })).Row);
grid_0979.Children.Add((new GridRow(0, new View[] { tbStudioSetPartMotionalSurroundLR, slStudioSetPartMotionalSurroundLR })).Row);
grid_0983.Children.Add((new GridRow(0, new View[] { tbStudioSetPartMotionalSurroundFB, slStudioSetPartMotionalSurroundFB })).Row);
grid_0987.Children.Add((new GridRow(0, new View[] { tbStudioSetPartMotionalSurroundWidth, slStudioSetPartMotionalSurroundWidth })).Row);
grid_0991.Children.Add((new GridRow(0, new View[] { tbStudioSetPartMotionalSurroundAmbienceSendLevel, slStudioSetPartMotionalSurroundAmbienceSendLevel })).Row);
StudioSetPartEQ.Children.Add((new GridRow(0, new View[] { grid_1005, grid_1006, grid_1011, grid_1015, grid_1019, grid_1023, grid_1027, grid_1031 })).Row);
grid_1005.Children.Add((new GridRow(0, new View[] { cbStudioSetPartEQSwitch })).Row);
grid_1006.Children.Add((new GridRow(0, new View[] { textblock_1010, cbStudioSetPartEQLoqFreq })).Row);
grid_1011.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEQLowGain, slStudioSetPartEQLowGain })).Row);
grid_1015.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEQMidFreq, cbStudioSetPartEQMidFreq })).Row);
grid_1019.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEQMidGain, slStudioSetPartEQMidGain })).Row);
grid_1023.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEQMidQ, cbStudioSetPartEQMidQ })).Row);
grid_1027.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEQHighFreq, cbStudioSetPartEQHighFreq })).Row);
grid_1031.Children.Add((new GridRow(0, new View[] { tbStudioSetPartEQHighGain, slStudioSetPartEQHighGain })).Row);
Buttons.Children.Add((new GridRow(0, new View[] { grid_1038, grid_1044 })).Row);
grid_1038.Children.Add((new GridRow(0, new View[] { cbStudioSetSlot, textblock_1043, tbStudioSetName })).Row);
grid_1044.Children.Add((new GridRow(0, new View[] { btnFileSave, btnFileLoad, btnStudioSetSave, btnStudioSetDelete, btnStudioSetReturn })).Row);
